[workspace]

members = [
    "smwe_project",
    "smwe_rom",
]

[package]
name = "smw-editor"
version = "0.1.0"
authors = ["Adam Gąsior (Adanos020)", "Jakub Szewczyk (kubasz)"]
license = "MIT"
edition = "2018"
readme = "README.md"

[dependencies]
smwe_project = { path = "smwe_project" }
smwe_rom = { path = "smwe_rom" }

glium = "0.29.0"
imgui = "0.7.0"
imgui-glium-renderer = "0.7.0"
imgui-winit-support = "0.7.0"
inline_tweak = "1.0.8"
log = "0.4.14"
log4rs = "1.0.0"
nfd2 = "0.3.0"
num_enum = "0.5.1"
