[package]
name = "nsmwe_app"
version = "0.1.0"
authors = ["adanos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nsmwe_rom = { path = "../nsmwe_rom" }

glium = "0.27.0"
imgui = "0.5.0"
imgui-glium-renderer = "0.5.0"
imgui-winit-support = "0.5.0"
