"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
defaults:
  run:
    shell: bash

name: Lints - Clippy and Rustfmt

jobs:
  clippy:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install development libraries
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libglx-dev libgl1-mesa-dev libsdl2-dev libwayland-dev libx11-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
